QUOTES = [
    "'As I am, so are they; as they are, so am I.' Comparing others with oneself, do not kill nor cause others to kill.",
    "A disciplined mind brings happiness.",
    "A noble one produces an abundance of merit by having a compassionate mind towards all living beings.",
    "A wise person should be urgently moved on occasions that make for urgency.",
    "All experiences are preceded by mind, having mind as their master, created by mind.",
    "Ardently do today what must be done. Who knows? Tomorrow, death comes.",
    "Conquer anger with non-anger. Conquer badness with goodness. Conquer meanness with generosity. Conquer dishonesty with truth.",
    "Delight in heedfulness! Guard well your thoughts!",
    "Give, even if you only have a little.",
    "I do not dispute with the world; rather it is the world that disputes with me.",
    "If with a pure mind a person speaks or acts, happiness follows them like a never-departing shadow.",
    "In whom there is no sympathy for living beings: know him as an outcast.",
    "It is in the nature of things that joy arises in a person free from remorse.",
    "Just as a mother would protect her only child with her life, even so let one cultivate a boundless love towards all beings.",
    "Meditate… do not delay, lest you later regret it.",
    "One should train in deeds of merit—generosity, a balanced life, developing a loving mind—that yield long-lasting happiness.",
    "Purity and impurity depend on oneself; no one can purify another.",
    "Radiate boundless love towards the entire world…",
    "See them, floundering in their sense of mine, like fish in the puddles of a dried-up stream — and, seeing this, live with no mine, not forming attachment for states of becoming.",
    "Should a seeker not find a companion who is better or equal, let them resolutely pursue a solitary course.",
    "Should you find a wise critic to point out your faults, follow him as you would a guide to hidden treasure.",
    "Speak only endearing speech, speech that is welcomed. Speech, when it brings no evil to others, is a pleasant thing.",
    "The one in whom no longer exist the craving and thirst that perpetuate becoming; how could you track that Awakened one, trackless, and of limitless range.",
    "There is no fear for one whose mind is not filled with desires.",
    "To support mother and father, to cherish partner and children, and to be engaged in peaceful occupation — this is the greatest blessing.",
    "Understanding is the heartwood of well-spoken words.",
    "Whatever has the nature of arising has the nature of ceasing.",
    "Whatever is not yours: let go of it. Your letting go of it will be for your long-term happiness & benefit.",
    "Whatever precious jewel there is in the heavenly worlds, there is nothing comparable to one who is Awakened.",
    "Better than a thousand useless words is one useful word, upon hearing which one attains peace.",
    "It's a good thing to be satisfied with what one has.",
    "Let none find fault with others; let none see the omissions and commissions of others. But let one see one's own acts, done and undone.",
    "Should someone do good, let them do it again and again. They should develop this habit, for the accumulation of goodness brings joy.",
    "The Enlightened One is deep, boundless, hard to fathom, like the ocean.",
    "The thing that is disliked by me is also disliked by others. Since I dislike this thing, how can I inflict it on someone else?",
    "'All conditioned things are impermanent' — when one sees this with wisdom, one turns away from suffering.",
    "'As I am, so are these. As are these, so am I.' Drawing the parallel to yourself, neither kill nor get others to kill.",
    "A mind unruffled by the vagaries of fortune, from sorrow freed, from defilements cleansed, from fear liberated — this is the greatest blessing.",
    "All tremble at violence; all fear death. Putting oneself in the place of another, one should not kill nor cause another to kill.",
    "As a water bead on a lotus leaf, as water on a red lily, does not adhere, so the sage does not adhere to the seen, the heard, or the sensed.",
    "As an elephant in the battlefield withstands arrows shot from bows all around, even so shall I endure abuse.",
    "Better it is to live one day seeing the rise and fall of things than to live a hundred years without ever seeing the rise and fall of things.",
    "Both formerly and now, it is only suffering that I describe, and the cessation of suffering.",
    "Ceasing to do evil, Cultivating the good, Purifying the heart: This is the teaching of the Buddhas.",
    "Drop by drop is the water pot filled. Likewise, the wise man, gathering it little by little, fills himself with good.",
    "Hatred is never appeased by hatred in this world. By non-hatred alone is hatred appeased. This is a law eternal.",
    "Having gone on his almsround, the sage should then go to the forest, standing or taking a seat at the foot of a tree. The enlightened one, intent on jhana, should find delight in the forest, should practice jhana at the foot of a tree, attaining his own satisfaction.",
    "He who can curb his wrath as soon as it arises, as a timely antidote will check snake's venom that so quickly spreads, — such a monk gives up the here and the beyond, just as a serpent sheds its worn-out skin.",
    "I will not look at another's bowl intent on finding fault: a training to be observed.",
    "If a man going down into a river, swollen and swiftly flowing, is carried away by the current — how can he help others across?",
    "If they are neither traceable in the Discourses nor verifiable by the Discipline, one must conclude thus: 'Certainly, this is not the Blessed One's utterance'",
    "Irrigators channel waters; fletchers straighten arrows; carpenters bend wood; the wise master themselves.",
    "Just as a solid rock is not shaken by the storm, even so the wise are not affected by praise or blame.",
    "Just as the great ocean has one taste, the taste of salt, so also this teaching and discipline has one taste, the taste of liberation.",
    "Know from the rivers in clefts and in crevices: those in small channels flow noisily, the great flow silent. Whatever's not full makes noise. Whatever is full is quiet.",
    "Let all-embracing thoughts for all beings be yours.",
    "Let none find fault with others; let none see the omissions and commissions of others. But let one see one's own acts, done and undone.",
    "May all beings have happy minds.",
    "One is not called noble who harms living beings. By not harming living beings one is called noble.",
    "Over there are the roots of trees; over there, empty dwellings. Practice meditation, monks. Don't be heedless.",
    "Radiate boundless love towards the entire world — above, below, and across — unhindered, without ill will, without enmity.",
    "Resolutely train yourself to attain peace.",
    "Should a person do good, let him do it again and again. Let him find pleasure therein, for blissful is the accumulation of good.",
    "Some do not understand that we must die, But those who do realize this settle their quarrels.",
    "The calmed say that what is well-spoken is best; second, that one should say what is right, not unrighteous; third, what's pleasing, not displeasing; fourth, what is true, not false.",
    "The root of suffering is attachment.",
    "The world is afflicted by death and decay. But the wise do not grieve, having realized the nature of the world.",
    "They blame those who remain silent, they blame those who speak much, they blame those who speak in moderation. There is none in the world who is not blamed.",
    "Those who cling to perceptions and views wander the world offending people.",
    "To support mother and father, to cherish wife and children, and to be engaged in peaceful occupation — this is the greatest blessing.",
    "We will develop and cultivate the liberation of mind by lovingkindness, make it our vehicle, make it our basis, stabilize it, exercise ourselves in it, and fully perfect it.",
    "When watching after yourself, you watch after others. When watching after others, you watch after yourself.",
    "Whoever doesn't flare up at someone who's angry wins a battle hard to win.",
    "You yourself must strive. The Buddhas only point the way.",
]
